jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          cd "${{ parameters.src }}"
          npm install
          npm run build
        displayName: 'Install Dependencies and Build Frontend (Vue Based Web App)'