jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion 
        inputs: 
          preferBundledVersion: false
      - task: DotNetCoreCLI@2
        displayName: "Restore project"
        inputs:
          command: "restore"
          projects: "src/${{ parameters.service }}/${{ parameters.service }}.csproj"
          feedsToUse: "select"
          vstsFeed: "fa1af919-202e-4e5c-91a7-dafe6f7d519e"
          versioningScheme: byBuildNumber
      - task: DotNetCoreCLI@2
        displayName: "dotnet build"
        inputs:
          command: "build"
          projects: "src/${{ parameters.service }}/${{ parameters.service }}.csproj"
          arguments: "--configuration Release /p:Version=$(GitVersion.NuGetVersion)"
          versioningScheme: byBuildNumber
      - task: DotNetCoreCLI@2
        displayName: 'dotnet pack' 
        inputs: 
          command: pack
          packagesToPack: "src/${{ parameters.service }}/${{ parameters.service }}.csproj"
          versioningScheme: byEnvVar 
          versionEnvVar: GitVersion.NuGetVersion
      - task: DotNetCoreCLI@2 
        displayName: 'dotnet nuget push' 
        inputs: 
          command: push 
          publishVstsFeed: 'Theatreers.Artifacts' 
          versioningScheme: byBuildNumber