variables:
  artifactName: 'drop'
  service: Theatreers.Show
  system.debug: true

trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - src/Theatreers.Show/*
    - /pipelines/Theatreers.Show.yml
    - /pipelines/Theatreers.Show/*
pr:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - src/Theatreers.Show/*
    - /pipelines/Theatreers.Show.yml
    - /pipelines/Theatreers.Show/*

stages:
- template: /pipelines/stages/lifecycle.yml
  parameters:
    service: ${{ variables.service }}