variables:
  service: Theatreers.Admin

trigger:
  batch: true
  branches:
    include:
    - ref/head/master
    - ref/head/feature/*
  paths:
    include:
    - /src/Theatreers.Admin/*
    - /pipelines/Theatreers.Admin/*

stages:
- template: /pipelines/stages/lifecycle.yml
  parameters:
    service: ${{ variables.service }}