variables:
  artifactName: "drop"
  applicationServiceNameFull: "Theatreers.Admin"
  applicationServiceNameShort: "Admin"
  azureServiceGroupName: "admin"
  src: "src/Theatreers.Admin/"
  system.debug: true

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - src/Theatreers.Admin/*
      - /pipelines/Theatreers.Admin.yml
      - /pipelines/Theatreers.Admin/*
pr:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - src/Theatreers.Admin/*
      - /pipelines/Theatreers.Admin.yml
      - /pipelines/Theatreers.Admin/*

stages:
  - template: /pipelines/stages/lifecycle.yml
    parameters:
      artifactName: ${{ variables.artifactName }}
      azureServiceGroupName: ${{ variables.azureServiceGroupName }}
      regions: [
        { "short": "neu", "long": "northeurope"},
        { "short": "weu", "long": "westeurope" }
      ]
      service: ${{ variables.applicationServiceNameFull }}
      src: ${{ variables.src }}