variables:
  service: Theatreers.Admin
  system.debug: true

trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - src/Theatreers.Admin/*
    - /pipelines/Theatreers.Admin.yml
    - /pipelines/Theatreers.Admin/*
pr:
  - master
  - feature/*

stages:
- template: /pipelines/stages/lifecycle.yml
  parameters:
    service: ${{ variables.service }}