variables:
  artifactName: "drop"
  applicationServiceNameFull: "Theatreers.Core"
  applicationServiceNameShort: "Core"
  azureServiceGroupName: "core"
  src: "src/Theatreers.Core/"
  system.debug: true

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - src/Theatreers.Core/*
      - /pipelines/Theatreers.Core.yml
      - /pipelines/Theatreers.Core/*
pr:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - src/Theatreers.Core/*
      - /pipelines/Theatreers.Core.yml
      - /pipelines/Theatreers.Core/*

stages:
  - template: /pipelines/stages/lifecycle.yml
    parameters:
      artifactName: ${{ variables.artifactName }}
      azureServiceGroupName: ${{ variables.azureServiceGroupName }}
      regions: [
        { "short": "neu", "long": "northeurope"}
      ]
      service: ${{ variables.applicationServiceNameFull }}
      src: ${{ variables.src }}
